name: push-actions
run-name: ${{ github.actor }} new git push
on: workflow_dispatch
jobs:
    update-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Update
              uses: actions/checkout@v4
            - run: echo "updating subject.md"
            - run: pydoc-markdown -m classes/subject.py -I $(pwd) > docs/subject.md
