name: push-actions
run-name: ${{ github.actor }} new git push
on: [push]
jobs:
    update-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Update
              uses: actions/checkout@v4
            - run: echo "updating subject.md"
            - run: pip install pydoc-markdown
            - run: pydoc-markdown -m classes/subject -I $(pwd) > docs/subject.md
            - run: git commit -m "updated docs"
            - run: git push -b dev
