name: push-actions
run-name: ${{ github.actor }} new git push
on: [push]
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Install
              uses: actions/checkout@v4
            - run: |
                pip install pydoc-markdown
                pydoc-markdown -m classes/subject -I $(pwd) > docs/subject.md
            - uses: stefanzweifel/git-auto-commit-action@v5
