name: push-actions
run-name: ${{ github.actor }} new git push
on: [push]
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Install
              uses: actions/checkout@v4
            - run: pip install pydoc-markdown
    update-docs:
        needs: install
        runs-on: ubuntu-latest
        steps:
          - name: Update
            uses: actions/checkout@v4
          - run: pydoc-markdown -m classes/subject -I $(pwd) > docs/subject.md
    push:
        needs: [install, update-docs]
        runs-on: ubuntu-latest
        steps:
          - name: Push
            uses: actions/checkout@v4
          - run: |
              git config --global user.name "baubrey"
              git config --global user.email "baubrey1214@gmail.com"
              git add -A
              git commit -m "updated docs"
              git push -b dev
